### ISSUE TITLE
Podlove Subscribe Button

### ISSUE THREAD

**Issue by mabe-at** [podcasterei/website-quellcode#2]
Multiple Instanzen des Subscribe Button brauchen eine eindeutige ID als auch eindeutige JSON-Daten.
Momentan ist die ID immer 1 und die Podcastdaten werden immer in window.podcastData1 gespeichert.
Deswegen erscheint immer nur der zuletzt hinzugefügte Button, egal welchen man klickt.

**Comment by mabe-at** [comment]
Auf der eigentlichen Personen-Seite ist das gleiche.

**Comment by haslinger** [comment]
Jop, ist mittlerweile auch gefixt.

**Comment by mabe-at** [comment]
Stefan "Fast" Haslinger!
